import { TasksProvider } from "@/context/TasksContext";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { Toaster } from "./Toaster";
import Layout from "@/components/Layout";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <TasksProvider>
          <Navbar />
          <Layout>{children}</Layout>
          <Toaster />
        </TasksProvider>
      </body>
    </html>
  );
}
